---

catalina_home: /usr/local/tomcat

java_opts_base: >
        -Xms512M
        -Xmx{{tomcat_memory}}
        -Djava.rmi.server.hostname={{ remote_endpoint_ip }}
        -Ddatabase.hostURL={{webserver_database}}
        -Dappcfg={{catalina_home}}/appcfg
        -Dproject.basedir={{catalina_home}}
        -Dtomcat.home={{catalina_home}}
        -Djavax.net.ssl.keyStore={{catalina_home}}/conf/geoprism.ks
        -Djavax.net.ssl.keyStorePassword={{ssl_keystore_password}}
        -Dbirt-server=true
        -DFile.encoding=UTF-8      
        -Ddatabase.user={{db_user}}
        -Ddatabase.password={{db_pass}}
        -Ddatabase.port=5432
        -Demail.username={{ email_user | default('x') }}
        -Demail.password={{ email_pass | default('x') }}
        -Dbucket.name={{bucket_name | default('x')}}
        -Dsolr.enabled={{solr_enabled | default('false')}}
        -Dgeoprism.volume=/data/geoprism/misc
        -Dorientdb.root.password={{orientdb_root_pass | default('x')}}
        -Dorientdb.admin.password={{orientdb_app_pass | default('x')}}
        -DGEOSERVER_DATA_DIR=/data/geoserver/data

java_opts_prod: >
        {{java_opts_base}}
        -server
        {{tomcat_java_opts | default('')}}

java_opts_debug: >
        {{java_opts_base}}
        -Dcom.sun.management.jmxremote
        -Dcom.sun.management.jmxremote.port=9010
        -Dcom.sun.management.jmxremote.rmi.port=9010
        -Dcom.sun.management.jmxremote.local.only=false
        -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.ssl=false
        -Xdebug
        -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=8000
        {{tomcat_java_opts | default('')}}
