# This playbook scrapes the logs from the specified server and throws them into platform/logs
# TODO : stack dump : /usr/lib/jvm/java-8-oracle/bin/jcmd 1 Thread.print > stack2.out

- hosts: localhost
  vars:
    LOCAL_LOGS: ../target/logs
  tasks:
    - name: Create log directory
      file:
        path: "LOCAL_LOGS"
        state: directory

- name: Download Logs
  hosts: webservers
  vars: 
    CATALINA_HOME: /usr/local/tomcat
    LOCAL_LOGS: ../target/logs
    LOG_DIR: "{{LOCAL_LOGS}}/{{inventory_hostname}}-{{ ansible_date_time.date }}-{{ansible_date_time.hour}}-{{ansible_date_time.minute}}-{{ansible_date_time.second}}"
  tasks:
    - name: Delete log staging
      file: 
        state: absent
        path: /tmp/staging/logs
      become: yes
      become_method: sudo
    - name: Make staging
      file: 
        state: directory
        path: /tmp/staging/logs
      become: yes
      become_method: sudo
    - name: Produce thread dump
      shell: docker exec geoprism bash -c 'jstack 1 > logs/jstack.out'
      become: yes
      become_method: sudo
    - name: Stage logs
      command: docker cp "geoprism:{{CATALINA_HOME}}/logs" /tmp/staging/logs/target
      become: yes
      become_method: sudo
      ignore_errors: yes
    - name: Add Geoprism container logs
      shell: docker logs geoprism --since 96h &> /tmp/staging/logs/docker-geoprism.log
      become: yes
      become_method: sudo
    - name: Add Postgres container logs
      shell: docker logs postgres --since 96h &> /tmp/staging/logs/docker-postgres.log
      become: yes
      become_method: sudo
    - name: Add Orientdb container logs
      shell: docker logs orientdb --since 96h &> /tmp/staging/logs/docker-orientdb.log
      become: yes
      become_method: sudo
    - name: Log staging permissions
      file: 
        state: directory
        path: /tmp/staging
        owner: "{{ansible_user}}"
        mode: 0700
        recurse: yes
      become: yes
      become_method: sudo
    - archive:
        path: /tmp/staging/logs/target
        dest: /tmp/staging/logs/logs.tgz
    - debug: msg="Downloading logs to {{LOG_DIR}}"
    - name: Download logs
      ansible.builtin.fetch:
        src: "/tmp/staging/logs/logs.tgz"
        dest: "{{LOG_DIR}}/logs.tgz"
        flat: yes
      become: yes
      become_method: sudo
